name: publish

on:
  push:
    branches:
      - publish
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/kentsday/dfx_rust:bullseye-dfx-0.10.1-1
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          cache-dependency-path: "src/package-lock.json"
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: "wasm32-unknown-unknown"
      - uses: Swatinem/rust-cache@v1
        with:
          working-directory: "src"
      - name: Setup .NET 5.0 for gittools
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "5.0.x"
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: 5.x
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true
      - name: create package
        run: |
          cd $GITHUB_WORKSPACE/src
          ./start_clean.sh
          ./sh_setup_dev.sh
      - run: |
          yarn install --frozen-lockfile
      - run: |
          npm config set always-auth true
          npm config set registry https:${REGISTRY}
          npm config set ${REGISTRY}:_authToken ${{ secrets.MY_GET_TOKEN }}
          npm config set @deland-labs:registry https:${REGISTRY}
        env:
          REGISTRY: //gitlab.com/api/v4/projects/37663507/packages/npm/
      - run: |
          cd $GITHUB_WORKSPACE/src
          Version=$(git describe --tags --abbrev=0)
          ./sh_publish.sh $Version
